version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DB: 'users'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
  spring-demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
    hostname: spring-demo
    ports:
      - "8080:8080"
    environment:
      - DB_IP=db
      - DB_PORT=3306
      - DB_DBNAME=users
      - DB_USER=root
      - DB_PASSWORD=admin
    networks:
      demo_net:

volumes:
  my-db:

networks:
  demo_net:
      external: true
